/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.sartellcoderdojo.groovybot

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        expect:
        app
        app.firstGuild
        app.firstChannel

        and:
        println(app.firstGuild)
        println(app.firstChannel)


    }
}
