/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.sartellcoderdojo.groovybot

import spock.lang.Specification

class AppTest extends Specification {
    def "application starts"() {
        setup:
        def app = new App()

        expect:
        app
    }
}
