/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.sartellcoderdojo.groovybot

import discord4j.core.*
import discord4j.core.object.entity.*
import discord4j.core.object.entity.channel.*
import discord4j.core.event.domain.message.*

class App {

    private final GatewayDiscordClient client
    private static final String TOKEN = 'BOT TOKEN'

    App() {
      client = DiscordClient.create(TOKEN).login().block()
      client.on(MessageCreateEvent).subscribe({handleMessage(it)})
    }

    static void main(String[] args) {
        new App()
        while(true) {

        }
    }

    Guild getFirstGuild() {
      client.getGuilds().blockFirst()
    }

    GuildChannel getFirstChannel() {
      firstGuild.channels.blockFirst()
    }

    void handleMessage(MessageCreateEvent event) {
      final Message message = event.getMessage();
      if ("!ping".equals(message.getContent())) {
        final MessageChannel channel = message.getChannel().block();
        channel.createMessage("Pong!").block();
      }
    }
}
